from .employees.employee_list import employee_list
from .home import home
from .auth.logout import logout_user
from .connection import Connection
from .training_programs.training_program_list import training_program_list
from .training_programs.training_program_form import training_program_form
from .training_programs.training_program_form import training_program_edit_form
from .training_programs.training_program_details import training_program_details
from .departments.department_list import department_list
from .employees.employee_details import employee_details
from .employees.form import employee_form
from .departments.department_form import department_form
from .computers.computer_list import computer_list
from .computers.computer_form import computer_form
from .employees.employee_training_program_form import employee_training_program_form
from .computers.computer_details import computer_details
